# Generated by Django 4.1.3 on 2022-11-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cambios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.FloatField()),
                ("criado", models.DateTimeField(auto_now_add=True)),
                ("editado", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
